 CREATE TABLE QLSV;
 GO
 USE QLSV;
 GO


 CREATE TABLE KHOA(
 MAKHOA char(10),
 TENKHOA NVARCHAR(15),
 SDT NVARCHAR (10),
 );
 CREATE TABLE GIANGVIEN(
 TENGV NVARCHAR(20),
 MAGV NVARCHAR(15),
 NAMSINH INT,
 DIACHI NVARCHAR(10),
 MAKOA char(10),
 );
 CREATE TABLE SINHVIEN(
TENSV NVARCHAR(15),
MASV NVARCHAR(20),
QUEQUANSV NVARCHAR(30),
NAMSINH INT,
);
insert into KHOA values
('IT' , N'CÔNG NGHỆ THÔNG TIN' , '0967810987'),
('OTO' , N'CÔNG NGHỆ OTO' , '0979162865')

insert into GIANGVIEN values
(01, N' NGUYỄN VĂN TÊN', '2004', 'GIA LAM', 'IT'),
(02, N'NGUYỄN VĂN DƯƠNG', '2000', 'NINH BINH', 'OTO')

insert into SINHVIEN
(01, N'NGUYỄN HOÀNG ANH' , 'BAC NINH' , '2005'),
(02, N'NGUYỄN ĐỨC ANH' , ' GIA LAM' , '2006')

select * from KHOA
select * from GIANGVIEN
select * from SINHVIEN